### ISSUE TITLE
Apurinã keyboard does not install on Windows 10

### ISSUE THREAD

**Issue by rueter** [divvun/kbdi#18]
A new version of the keyboard-apu has been successfully generated for Windows, 2024-05-28.
(1) install Divvun Manager and restart Windows 10.
(2) select nightly, and download Apurinã keyboard on Divvun Manager.
(3) from «Start» left-click «Apurinã keyboard», right-click «enable Apurinã»/more/
select ~«install as administrator»
(4) Answer non-default «Yes» two times
(5) restart computer
(6) settings/time and language/  select «language» >> Portuguese
(7) Portuguese options, but no Apurinã.
(8) install Nuõrtsääʹm keyboard using Divvun Manager,
(9) repeat steps (3)–(6) for Skolt Saami keyboard
(10) Portuguese options, Nuõrtsääʹm
(11) write in new document, install Skolt speller, both the Skolt keyboard and the Skolt speller work.

On, Home Win10 Apurinã and Lushootseed do not install. @snomos has suggested that the absence of Apurinã might be do to it not being present in the Micro Soft list of languages.

**Comment by rueter** [comment]
(4) above

![apu_admin_install_eng_home2024-05-30](https://github.com/divvun/kbdi/assets/14276164/7bebdacc-6a24-4748-a8ab-6721518c1223)
Enable as Admin
The issue on Rueter's Win10.

![apu_install_as_admin_2024-05-30](https://github.com/divvun/kbdi/assets/14276164/1b26dbab-bb12-44ea-92df-ffec1303bcf9)
Enable as Admin
The same issue attested on a Brazilian user's (Ana Vilacy) machine (Win10).

Go through the motions of installing and enabling on two separate Win10 machines, but no result is observed.

**Comment by rueter** [comment]
(3) above
![apu_enable_as_admin_vilacy](https://github.com/divvun/kbdi/assets/14276164/541ab0a3-e9ef-4fbc-94b3-1acfb31d4b75)
Enable as admin

![apu_keyboardversion_vilacy](https://github.com/divvun/kbdi/assets/14276164/ceca0c92-e5a1-4e85-bf94-ebd3c0b445b5)
Keyboard-apu version is 2024-05-28

![apu_not_option_vilacy](https://github.com/divvun/kbdi/assets/14276164/17efa566-113b-486a-89ae-bec8d4759ae4)
Search for the Apurinã keyboard as an option, but it is not there.
(7) above

**Comment by rueter** [comment]
Using Divvun Manager (Windows) to download the following keyboards implies importing keyboards that might be enabled:
apu, fkv, izh, krl, liv, mns, mrj, olo, sjd, tqn, tyv, vro.
All of these keyboards were subsequently run as administrator after rebooting.
None of these keyboards were made available for selection under:
time and language/language/{Finnish|English (US)}/options/Add keyboard.

I would have expected fkv, vro and mns to appear

**Comment by dylanhand** [comment]
Hi @rueter - I'm looking into this. First time dealing with Windows keyboard installs and kbdi and I have a few questions.

1. It looks like Skolt Sami keyboards are built into Windows 10. When I go to Settings > Time & Language > "Add a language" and search, it appears before I even install Divvun Manager. Is this expected or am I looking in the right place? I mention this to say that perhaps Skolt Sami keyboards aren't working either.
![CleanShot 2024-06-10 at 10 46 21@2x](https://github.com/divvun/kbdi/assets/431529/6bc7bd1e-2167-4074-9903-fbdc5a0d61e4)

2. 
> (6) settings/time and language/ select «language» >> Portuguese

Can you help me understand why it's necessary to set the language to Portuguese?

To clarify, what are the usual steps to enable a keyboard that's just been installed by Divvun Manager? I'm guessing it's to enable that language in Settings > Time & Language > Add a language, and then it's possible to select the keyboard in the language list at the bottom right in the task bar?

**Comment by snomos** [comment]
@dylanhand the usual steps should be:

1. install Divvun Manager
2. install the desired keyboard (this installs also `kbdi`, and registers the new language)
3. run the activator script via the Start/Windows menu (this makes the new language accessible to the user, for that specific user account)
4. restart the computer

The OneClick installer was made to automate steps 1.-3., so that one only has one step to do + restart(?).

The issue @rueter describes is that for whatever reason, step 3. above does not seem to do anything. It might be that the bug is in step 2. but that is impossible for users to know.

**Comment by rueter** [comment]
Hi, Dylan!

To address your question.
To my understanding, Divvun Manager provides languages that otherwise do
not appear on Windows in the settings/time and Language/Language/Add
language.

Languages introduced by the Divvun Manager and enabled will appear here:
settings/time and Language/Language/{Selected language: English, Finnish,
Brazilian}/Options/Add keyboard

This means that, in  the same place I can insert a Chinese keyboard under
my Brazilian or English keyboard, I can also opt to insert the Apurinã
keyboard.

Did this help?

Jack

**Comment by dylanhand** [comment]
Thanks for both of your clarifications @snomos @rueter :)

My understanding then is that, if the keyboard were installed correctly, the user would be able to enable it by 
1.  Going to Settings > Time & Language > Language, then selecting an already-enabled language (in my case English), and selection "Options" (first screenshot)
2.  Scrolling down to "Add a keyboard" (second screenshot)

![Screenshot (5)](https://github.com/divvun/kbdi/assets/431529/911bd76b-ff40-405b-ae94-dadf65388090)
![Screenshot (6)](https://github.com/divvun/kbdi/assets/431529/d0264d43-3e2c-4a0b-b01d-ec9a688d8c10)


Is that correct?

**Comment by rueter** [comment]
Yes, Dylan!
You have understood me correctly.

**Comment by dylanhand** [comment]
Great, thanks for the clarification @rueter!

**Comment by snomos** [comment]
@dylanhand that is not how I have enabled keyboards earlier, I only use that method for keyboards provided by Microsoft. It _might_ work, but I can't verify that. Instead, what I have done earlier, and which is the way it must be done for languages for which Microsoft does not have any keyboard, is to:

1. install the keyboard using Divvun Manager
2. Activate the keyboard using the activation script, available via the Windows menu

This is what Brendan wrote to me off-line:

> really the only way to enable the keyboards is with the enablement shortcuts, which presumably aren't easy to find since Windows 10 and 11 changed how the start menu worked pretty significantly

**Comment by rueter** [comment]
Perhaps, this is a bit of random information, but in the keyboards
downloaded via the Mac Divvun Manager, there seems to be a latent reference
to a US keyboard. The screenshot here illustrates what is shown on the mac
screen when the machine wakes up from sleep. Here, the keyboard used before
the machine went to sleep was Võro.
I am thinking that there might be this kind of US-hinging in the Windows
side as well.

Jack

**Comment by dylanhand** [comment]
Thanks for the info @snomos. 

Then it sounds like the keyboard is directly enabled by installing it via the start menu item. In other words, that the user does not have to do anything to actually enable the keyboard in settings - rather that is done for them when they run the start menu item as administrator.

Good to know. I'll be looking at the `kbdi` code to see how it works.

**Comment by dylanhand** [comment]
This should now be fixed. I've tested with [`keyboard-sjd`](https://github.com/giellalt/keyboard-sjd) and [`keyboard-apu`](https://github.com/giellalt/keyboard-apu). 

Note that in my testing, installing and enabling `keyboard-apu` worked without restart, but installing and enabling `keyboard-sjd` required a restart before it appeared in the Windows 10 language menu at the bottom right.

@snomos can you please trigger builds for and test any other offending keyboards and close if complete? 

Note that Divvun Manager on Windows needed to be force refreshed in my experience to be able to see the new nightly builds. 

Force refresh like so:
1. open settings and change to stable channel
2. go back to basic view (not all repos) 
3. open settings and change back to nightly
4. switch ui back to All Repositories view

Let's also keep an eye out to make sure the changes don't cause problems with already working keyboards.

For sake of documentation, this was the fix: https://github.com/divvun/taskcluster-gha/commit/07cf26937d3481b24b46749912c1bcf271725ba5.

**Comment by rueter** [comment]
Yes!!!!
apu works.
Two screen shots show that there is still a problem/feature to deal with,
i.e., OL means other language, so I have to know whether vro is above and
apu is below. Maybe, others will not be using multiple keyboards to the
extent I am.

Jack

**Comment by rueter** [comment]
@dylanhand and @snomos 
(1) Today, I was able to down load the keyboard for mdf.
(2) vro appears as a faded choice in language selections. It is like a shell with nothing for the language itself.
(3) I downloaded but had no success with: esu, fit, hdn, izh_EE, krl, lut, mhr, mns, mrj, niv, olo, tqn, tyv, vot as well as keyboards for Buryat, and a few other languages: Kiowa, Tanana, Tsuutina...
In (3), I am able to administrator-activate the keyboards under start, but they never appear as languages or options under languages.

**Comment by snomos** [comment]
> In (3), I am able to administrator-activate the keyboards under start,

Good

> but they never appear as languages or options under languages.

What language options are you talking about? Can you send a screen shot?

The only (but important) place to find the newly enabled keyboard is in the keyboard menu.

**Comment by rueter** [comment]
Languages include these: English (US), FInnish, ?Voro, Apurinã, Kildin Sami, Lule Sami.
Võro does not really exist.
![DM_apu_sjd_2024-06-20_not_others](https://github.com/divvun/kbdi/assets/14276164/4625e44b-4cec-4fc2-9dbb-a0c0a198959c)

**Comment by dylanhand** [comment]
@rueter 

> Yes!!!!
> apu works.

Glad to hear it!

> (3) I downloaded but had no success with: esu, fit, hdn, izh_EE, krl, lut, mhr, mns, mrj, niv, olo, tqn, tyv, vot as well as keyboards for Buryat, and a few other languages: Kiowa, Tanana, Tsuutina...

Note that for any of these keyboards to work, a new build will need to be triggered. I can see that [keyboard-esu hasn't been built in 4 months](https://github.com/giellalt/keyboard-esu), for example. 

I've just triggered new builds for the following keyboards:
1. fit
2. esu
3. hdn
4. izh_EE
5. krl
6. lut
7. mhr
8. mns
9. mrj
10. niv
11. olo
12. tqn
13. tyv
14. vot

I did not trigger for the ones you mentioned without language codes but I'm sure @snomos can find and trigger those ones:)

After these keyboards have been rebuilt, make sure to follow the force-refresh instructions in Divvun Manager:

>Force refresh like so:
> 1.   open settings and change to stable channel
> 2.   go back to basic view (not all repos)
> 3.   open settings and change back to nightly
> 4.   switch ui back to All Repositories view

I'm on vacation until July 18, but @snomos feel free to get in touch with Urban if you need anything. Hope this helps and glad midsommar!

**Comment by rueter** [comment]
I'll start listing the languages that show up:
Apurinã (apu-Latn-BR)
Central Yupik (esu-Latn-US)
Eastern Mari (mhr-Cyrl-RU)
Karelian (krl-Latn-FI)
Livvi (olo-Latn)
Lushootseed (lut-Latn-US)
Mansi (mns-Cyrl-RU)
Northern Haida (hdn-Latn-CA)
Plains Cree (crk-Cans)
Votic (vot-Latn)
Western Mari (mrj-Cyrl)
![DM_apu_esu_lut_mhr_mns_olo2024-06-21](https://github.com/divvun/kbdi/assets/14276164/90739eb6-0465-4618-a962-7eeff20a83ea)

Under the options of an individual language (Finnish, here) I am able to select the following keyboards:
apu, crk, esu, hdn, krl, lut, mdf, mhr, mns, myv, olo, sjd, vot.

**Comment by rueter** [comment]
@snomos, here is a list of the keyboards that have yet to be triggered for a rebuild:
bla, bxr, ckt, crk, dag, fit, fkv, gur, ike, kio, mdf, myv, srs, tau, tqn, tyv, urj
